name: Build, publish and deploy to MonsterASP.NET
on: [push]
jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Test with .NET
        run: dotnet test --no-restore
        
      - name: Publish
        run: dotnet publish --configuration Release --output publish --runtime win-x86 --self-contained false --no-restore
        
      - name: List files (debug)
        run: |
          echo "Current directory:"
          dir
          echo "Publish folder contents:"
          dir publish
        
      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: 'publish'
