name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore olx-api.csproj
      
    - name: Build
      run: dotnet build olx-api.csproj --configuration Release --no-restore
      
    - name: Test (if you have tests)
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
      
    - name: Publish
      run: dotnet publish olx-api.csproj --configuration Release --output ./publish --no-restore
